name: PHP Composer Test

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     branches:    
      - master  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # List all installed PHP Libraries
    - name: List all installed PHP Libraries
      run: |
        echo "Installed PHP Libraries:" && dpkg --get-selections | grep -iE "(php|pear)" | sort
        echo "Installed Docker Libraries:" && dpkg --get-selections | grep -iE (docker|container)" | sort
        
    # Install missing PHP Libraries
    - name: Install docker-compose Library
      run: |
        sudo apt-get update
        echo "Available Docker Libraries:" && apt-cache search docker | sort
        echo "Library 'docker-compose': installing ..." && sudo apt-get install docker-engine docker-compose   
    
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress --no-suggest

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
